substitutions:
  devicename:   controlpad
  upper_devicename: Control Pad
  ip_address: "192.168.2.88"
    
esphome:
  name: $devicename
  platform: ESP32
  board: esp32-evb

<<: !include common/common.yaml

binary_sensor:
  - platform: gpio
    name: "gpio23"
    pin: GPIO23
    
  - platform: gpio
    name: "gpio23"
    pin: GPIO23
