esphome:
  name: controlpad
  platform: ESP32
  board: esp32-evb

wifi:
  networks:
  - ssid: !secret wifi_ssid 
    password: !secret wifi_password 
  - ssid: !secret wifi2_ssid 
    password: !secret wifi2_password 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ControlpadFB"
    password: "123459876"
        
  manual_ip:
    static_ip: 192.168.2.88
    gateway: 192.168.2.1
    subnet: 255.255.255.0
    
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "garden61"

ota:
  password: "garden61"
