version: '3'

services:
  esphome:
    container_name: esphome  
    image: esphome/esphome
    restart: unless-stopped
    # user: "1000"
    #devices:
     # - /dev/ttyUSB0:/dev/ttyUSB0
    #environment:
      #- TZ=America/Los_Angeles # offset = -08:00 / DST -07:00
    network_mode: host
    #ports:
      #- 6052:6052
    volumes:
      # Use local time for logging timestamps
      - /etc/localtime:/etc/localtime:ro
      - ./:/config:rw
