esphome:
  name: test
  platform: ESP32
  board: esp32-devkitlipo

wifi:
  ssid: "garden61"
  password: "garden61"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "wy325lLxDrto"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
